### ISSUE TITLE
Takk!

### ISSUE THREAD

**Issue by v0iden** [FilipNilsen/inschool-to-ical#1]
Skulle til å lage en (halv-automatisk?) webscraper for å få timeplanen inn i google calendar, men nå ser det ut som jeg slipper! Takk skal du ha!

**Comment by FilipNilsen** [comment]
Takk for tilbakemeldingen.
Vær oppmerksom på at jeg er ferdig på videregående og kan derfor ikke utvikle dette noe mer herifra.

**Comment by FilipNilsen** [comment]
Trykket med et uhell på 'Comment' istedenfor 'Close with comment'

**Comment by v0iden** [comment]
haha, jeg er ferdig på videregående jeg også. aner ikke hvorfor jeg begynte på dette med bare en drøy måned igjen i Vg3.. men, men. var gøy ihvertfall.
